#!/usr/bin/env python3
"""
generate_rules_appendix.py
Auto-generate Appendix A (the full BBCN digital logic model) directly from
setup_a/bbcn/pathways.py, so the printed rules can never drift from the code.

For each pathway it emits, for every node, a Boolean equation
    NODE = <formula over intra-pathway nodes and external bus inputs>
written with the words AND / OR / NOT, gene symbols verbatim.
Output: preprint/appendix_rules.tex  (\input by the manuscript).
"""
import ast, os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "setup_a", "bbcn", "pathways.py")
OUT = os.path.join(HERE, "preprint", "appendix_rules.tex")

src = open(SRC).read()
tree = ast.parse(src)


def render(node, nodes):
    """Translate an expression AST into a readable Boolean string."""
    if isinstance(node, ast.Call):
        f = node.func
        # int(...) wrapper -> render its single argument
        if isinstance(f, ast.Name) and f.id == "int":
            return render(node.args[0], nodes)
        # e_(e,'NAME') -> external bus input NAME
        if isinstance(f, ast.Name) and f.id == "e_":
            return ast.literal_eval(node.args[1])
        # fallback
        return ast.unparse(node)
    if isinstance(node, ast.BoolOp):
        op = " AND " if isinstance(node.op, ast.And) else " OR "
        parts = []
        for v in node.values:
            s = render(v, nodes)
            if isinstance(v, ast.BoolOp):
                s = "(" + s + ")"
            parts.append(s)
        return op.join(parts)
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not):
        s = render(node.operand, nodes)
        if isinstance(node.operand, (ast.BoolOp,)):
            s = "(" + s + ")"
        return "NOT " + s
    if isinstance(node, ast.Subscript):
        # x[i] -> nodes[i]
        if isinstance(node.value, ast.Name) and node.value.id == "x":
            idx = ast.literal_eval(node.slice)
            return nodes[idx]
        return ast.unparse(node)
    if isinstance(node, ast.Constant):
        return "1" if node.value in (1, True) else "0"
    if isinstance(node, ast.Name):
        return node.id
    return ast.unparse(node)


def pathway_info(fn):
    """From a _pathway() FunctionDef, return (nodes, role, sigma, rules_list, passthrough)."""
    rules_list = None
    passthrough = False
    meta = {}
    for n in ast.walk(fn):
        if isinstance(n, ast.FunctionDef) and n.name == "rules":
            ret = next(s for s in n.body if isinstance(s, ast.Return))
            if isinstance(ret.value, ast.List):
                rules_list = ret.value.elts
            else:
                # comprehension form [int(x[i]) for i in range(N)] -> pass-through inputs
                passthrough = True
    # the outer return dict
    outer_ret = [s for s in fn.body if isinstance(s, ast.Return)][-1]
    d = outer_ret.value
    for k, v in zip(d.keys, d.values):
        key = ast.literal_eval(k)
        if key in ("nodes", "role", "sigma_order"):
            try:
                meta[key] = ast.literal_eval(v)
            except Exception:
                meta[key] = None
    return meta.get("nodes"), meta.get("role"), meta.get("sigma_order"), rules_list, passthrough


pathways = []
for fn in tree.body:
    if isinstance(fn, ast.FunctionDef) and fn.name.startswith("_"):
        nodes, role, sigma, rules_list, passthrough = pathway_info(fn)
        if nodes and (passthrough or (rules_list and len(nodes) == len(rules_list))):
            pathways.append((sigma if sigma is not None else 999, fn.name, nodes, role, rules_list, passthrough))
pathways.sort(key=lambda t: t[0])


def texesc(s):
    return s.replace("_", r"\_")


lines = []
lines.append("% AUTO-GENERATED by generate_rules_appendix.py from setup_a/bbcn/pathways.py -- DO NOT EDIT BY HAND.")
lines.append(r"\section{The BBCN digital logic model}")
lines.append(r"\label{app:rules}")
lines.append(r"This appendix lists the complete Boolean update logic of the BBCN network, "
             r"one block per pathway module, generated directly from the source file "
             r"\texttt{pathways.py} so that the printed rules cannot drift from the code. "
             r"For each node, the right-hand side is its update rule over intra-pathway nodes and "
             r"external bus inputs; \texttt{AND}, \texttt{OR}, \texttt{NOT} are the Boolean connectives. "
             r"A node with rule equal to a single input is a pass-through of that input.")
lines.append("")
ncount = 0
for sigma, fname, nodes, role, rules_list, passthrough in pathways:
    title = fname.lstrip("_").replace("_", " ").upper()
    rolestr = (" (%s)" % role) if role else ""
    lines.append(r"\paragraph{%s.%s}\mbox{}\\" % (texesc(title), texesc(rolestr)))
    lines.append(r"\begin{flushleft}\ttfamily\small")
    for i, nd in enumerate(nodes):
        if passthrough:
            rhs = nd + "  (external input)"
        else:
            rhs = render(rules_list[i], nodes)
        lines.append(r"%s = %s\\" % (texesc(nd), texesc(rhs)))
        ncount += 1
    lines.append(r"\end{flushleft}")
    lines.append("")

lines.append(r"\noindent\textit{Total: %d nodes across %d pathway modules.}" % (ncount, len(pathways)))

open(OUT, "w").write("\n".join(lines))
print("WROTE", OUT)
print("pathways:", len(pathways), "| nodes:", ncount)
print("pathway order:", [p[1].lstrip('_') for p in pathways])
