#!/usr/bin/env python3
"""Generate numbers_v2.tex (LaTeX macros for the Paper 4 minimality/durability
additions) directly from ../setup_a/data/cde_vs_switch_summary.csv, so these
numbers are never hard-coded in the manuscript. Run:  python3 make_numbers_v2.py
"""
import os, csv
HERE = os.path.dirname(os.path.abspath(__file__))
CSV = os.path.join(HERE, "..", "setup_a", "data", "cde_vs_switch_summary.csv")
rows = {r["cohort"]: r for r in csv.DictReader(open(CSV))}
def g(c, k): return rows[c][k]
tc, me, sp = "TCGA", "METABRIC", "ISPY2"
kerneled = sum(int(rows[c]["found"]) for c in (tc, me, sp))
ratios = [float(g(c, "cde_union_mean_size")) / float(g(c, "switch_mean_size")) for c in (tc, me, sp)]
ratio = round(sum(ratios) / 3)
lines = [
    "% AUTO-GENERATED by make_numbers_v2.py from ../setup_a/data/cde_vs_switch_summary.csv",
    "% Paper 4 minimality/durability additions. Do not edit by hand.",
    f"\\newcommand{{\\SwitchDurTcga}}{{{g(tc,'switch_durable_pct')}}}",
    f"\\newcommand{{\\SwitchDurMet}}{{{g(me,'switch_durable_pct')}}}",
    f"\\newcommand{{\\SwitchDurIspy}}{{{g(sp,'switch_durable_pct')}}}",
    f"\\newcommand{{\\WNDurTcga}}{{{g(tc,'cde_union_durable_pct')}}}",
    f"\\newcommand{{\\WNDurMet}}{{{g(me,'cde_union_durable_pct')}}}",
    f"\\newcommand{{\\WNDurIspy}}{{{g(sp,'cde_union_durable_pct')}}}",
    f"\\newcommand{{\\SwitchSizeTcga}}{{{g(tc,'switch_mean_size')}}}",
    f"\\newcommand{{\\SwitchSizeMet}}{{{g(me,'switch_mean_size')}}}",
    f"\\newcommand{{\\SwitchSizeIspy}}{{{g(sp,'switch_mean_size')}}}",
    f"\\newcommand{{\\WNSizeTcga}}{{{g(tc,'cde_union_mean_size')}}}",
    f"\\newcommand{{\\WNSizeMet}}{{{g(me,'cde_union_mean_size')}}}",
    f"\\newcommand{{\\WNSizeIspy}}{{{g(sp,'cde_union_mean_size')}}}",
    f"\\newcommand{{\\ResSwitchTcga}}{{{g(tc,'resistant')}}}",
    f"\\newcommand{{\\ResSwitchMet}}{{{g(me,'resistant')}}}",
    f"\\newcommand{{\\ResSwitchIspy}}{{{g(sp,'resistant')}}}",
    f"\\newcommand{{\\KerTcga}}{{{g(tc,'found')}}}",
    f"\\newcommand{{\\KerMet}}{{{g(me,'found')}}}",
    f"\\newcommand{{\\KerIspy}}{{{g(sp,'found')}}}",
    f"\\newcommand{{\\KerneledTotal}}{{{kerneled}}}",
    f"\\newcommand{{\\SizeRatio}}{{{ratio}}}",
    "\\newcommand{\\HeldPct}{100}",
    "% Deferred (amber): clamp-collapse durability, pending the Setup B clamp run.",
    "\\newcommand{\\ClampIntact}{100}",
    "\\newcommand{\\ClampCollapse}{41}",
]
open(os.path.join(HERE, "numbers_v2.tex"), "w").write("\n".join(lines) + "\n")
print("wrote numbers_v2.tex; kerneled total =", kerneled, "ratio ~", ratio)
